export type ApplicationStatus =
  | 'SUBMITTED'
  | 'UNDER_REVIEW'
  | 'SHORTLISTED'
  | 'ACCEPTED'
  | 'REJECTED'
  | 'WITHDRAWN';


export type MissingSkillImportance =
  | 'LOW'
  | 'MEDIUM'
  | 'HIGH'
  | 'CRITICAL';


export interface Application {

  id: number;

  candidateId: number;

  jobOfferId: number;

  status: ApplicationStatus;

  coverLetter?: string;

  appliedAt: string;

  reviewedAt?: string;

  updatedAt: string;

}


/*
 * final_score is generated by MySQL from
 * (skillScore * 0.50) + (experienceScore * 0.30) + (educationScore * 0.20)
 * (master prompt Section 27) — treat as read-only on the frontend.
 */

export interface MatchingResult {

  id: number;

  applicationId: number;

  skillScore: number;

  experienceScore: number;

  educationScore: number;

  finalScore: number;

  explanation?: string;

  algorithmVersion: string;

}


export interface MissingSkill {

  id: number;

  matchingResultId: number;

  skillId: number;

  importance: MissingSkillImportance;

}
