-- ============================================================
-- SmartRecruit AI — OPTIONAL Demo/Test Data v1.0
-- Execute AFTER schema.sql and seed.sql.
--
-- Password hashes below are intentionally placeholders.
-- In the real app, users MUST be created through Spring Boot
-- with BCrypt. This file is only for relational/database tests.
-- ============================================================

USE smartrecruit;

-- Company
INSERT INTO companies
(name, description, city, country, industry, status)
VALUES
(
    'Tech Solutions',
    'Demo software company for SmartRecruit AI.',
    'Casablanca',
    'Morocco',
    'Software',
    'ACTIVE'
);

SET @company_id = LAST_INSERT_ID();

-- Candidate user
INSERT INTO users
(first_name, last_name, email, password_hash, phone, role, status)
VALUES
(
    'Ahmed',
    'Alami',
    'ahmed.demo@smartrecruit.test',
    '$2a$10$DEMO_HASH_REPLACE_USING_SPRING_BOOT',
    '0612345678',
    'CANDIDATE',
    'ACTIVE'
);

SET @candidate_user_id = LAST_INSERT_ID();

INSERT INTO candidates
(user_id, city, country, bio, total_experience_months,
 highest_education_level, profile_completed)
VALUES
(
    @candidate_user_id,
    'Casablanca',
    'Morocco',
    'Demo Java backend candidate.',
    24,
    'BAC_3',
    TRUE
);

SET @candidate_id = LAST_INSERT_ID();

-- Recruiter user
INSERT INTO users
(first_name, last_name, email, password_hash, phone, role, status)
VALUES
(
    'Sara',
    'Bennani',
    'sara.demo@smartrecruit.test',
    '$2a$10$DEMO_HASH_REPLACE_USING_SPRING_BOOT',
    '0623456789',
    'RECRUITER',
    'ACTIVE'
);

SET @recruiter_user_id = LAST_INSERT_ID();

INSERT INTO recruiters
(user_id, company_id, position)
VALUES
(
    @recruiter_user_id,
    @company_id,
    'HR Manager'
);

SET @recruiter_id = LAST_INSERT_ID();

-- Candidate experience
INSERT INTO experiences
(candidate_id, job_title, company_name, start_date, end_date,
 is_current, duration_months, source)
VALUES
(
    @candidate_id,
    'Backend Developer',
    'ABC Company',
    '2024-01-01',
    '2026-01-01',
    FALSE,
    24,
    'MANUAL'
);

-- Candidate education
INSERT INTO educations
(candidate_id, degree, field, institution, start_year, end_year, level, source)
VALUES
(
    @candidate_id,
    'Bachelor in Computer Science',
    'Computer Science',
    'Demo University',
    2021,
    2024,
    'BAC_3',
    'MANUAL'
);

-- Candidate skills: Java, Spring Boot, MySQL
INSERT IGNORE INTO candidate_skills
(candidate_id, skill_id, level, source, confidence_score)
SELECT @candidate_id, id, 'INTERMEDIATE', 'MANUAL', 100
FROM skills
WHERE normalized_name IN ('java','spring boot','mysql');

-- Job offer
INSERT INTO job_offers
(recruiter_id, company_id, title, description, location,
 work_mode, contract_type, required_experience_years,
 required_education_level, salary_min, salary_max,
 status, published_at, deadline)
VALUES
(
    @recruiter_id,
    @company_id,
    'Java Backend Developer',
    'Demo Java Backend Developer position.',
    'Casablanca',
    'HYBRID',
    'CDI',
    2.0,
    'BAC_3',
    8000,
    12000,
    'PUBLISHED',
    CURRENT_TIMESTAMP,
    DATE_ADD(CURRENT_DATE, INTERVAL 30 DAY)
);

SET @job_id = LAST_INSERT_ID();

-- Required job skills
INSERT IGNORE INTO job_skills
(job_offer_id, skill_id, required_level, mandatory, weight)
SELECT @job_id, id,
       CASE
           WHEN normalized_name = 'docker' THEN 'BEGINNER'
           ELSE 'INTERMEDIATE'
       END,
       TRUE,
       CASE
           WHEN normalized_name = 'java' THEN 30
           WHEN normalized_name = 'spring boot' THEN 30
           WHEN normalized_name = 'mysql' THEN 20
           WHEN normalized_name = 'docker' THEN 20
       END
FROM skills
WHERE normalized_name IN ('java','spring boot','mysql','docker');

-- Application
INSERT INTO applications
(candidate_id, job_offer_id, status, cover_letter)
VALUES
(
    @candidate_id,
    @job_id,
    'UNDER_REVIEW',
    'I am interested in this demo position.'
);

SET @application_id = LAST_INSERT_ID();

-- Matching result:
-- Skills 75, Experience 100, Education 100
-- final_score is GENERATED by DB => 87.50
INSERT INTO matching_results
(application_id, skill_score, experience_score, education_score,
 explanation, algorithm_version)
VALUES
(
    @application_id,
    75,
    100,
    100,
    'Candidate matches Java, Spring Boot and MySQL. Docker is missing.',
    'v1.0'
);

SET @matching_id = LAST_INSERT_ID();

-- Missing Docker
INSERT INTO missing_skills
(matching_result_id, skill_id, importance)
SELECT @matching_id, id, 'HIGH'
FROM skills
WHERE normalized_name = 'docker';

-- Job recommendation
INSERT INTO job_recommendations
(candidate_id, job_offer_id, recommendation_score, reason)
VALUES
(
    @candidate_id,
    @job_id,
    87.50,
    'Strong compatibility with the candidate backend profile.'
);

-- Docker training recommendation
INSERT INTO training_recommendations
(candidate_id, training_id, recommendation_score, reason)
SELECT
    @candidate_id,
    id,
    95,
    'Docker is missing from the candidate profile.'
FROM trainings
WHERE title = 'Docker Fundamentals'
LIMIT 1;

-- Quick verification
SELECT * FROM vw_candidate_profiles;
SELECT * FROM vw_published_jobs;
SELECT * FROM vw_job_candidate_ranking;
SELECT * FROM vw_candidate_missing_skills;

-- ============================================================
-- END demo_seed.sql
-- ============================================================
